//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.31 at 10:02:19 AM CEST 
//


package igeriv.dpe.it.inforiv.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://it.dpe.igeriv/inforiv/schemas}EdicolaInforiv"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "edicolaInforiv"
})
@XmlRootElement(name = "EdicolaInforivRequest")
public class EdicolaInforivRequest {

    @XmlElement(name = "EdicolaInforiv", required = true)
    protected EdicolaInforiv edicolaInforiv;

    /**
     * Gets the value of the edicolaInforiv property.
     * 
     * @return
     *     possible object is
     *     {@link EdicolaInforiv }
     *     
     */
    public EdicolaInforiv getEdicolaInforiv() {
        return edicolaInforiv;
    }

    /**
     * Sets the value of the edicolaInforiv property.
     * 
     * @param value
     *     allowed object is
     *     {@link EdicolaInforiv }
     *     
     */
    public void setEdicolaInforiv(EdicolaInforiv value) {
        this.edicolaInforiv = value;
    }

}
