package it.dpe.inforiv.util;

import java.util.HashMap;

import org.springframework.stereotype.Component;

@Component("SegmentiDiMercatoInforete")
public class SegmentiDiMercatoInforete extends HashMap<Integer, String> {
	private static final long serialVersionUID = 1L;
	
	public SegmentiDiMercatoInforete() {
		put(1,"Pornografia");
		put(2,"Pornografia FUMETTI");
		put(3,"Pornografia BUSTE");
		put(4,"Pornografia Video cassette");
		put(5,"Riviste FEMMINILI");
		put(6,"Riviste RAGAZZI/GIOVANI");
		put(7,"Riviste POLITICA/ECONOMIA");
		put(8,"Riviste TURISMO/VIAGGI");
		put(9,"Riviste PROGRAMMI  TELEVISIVI");
		put(10,"Riviste COLLEZIONABILI");
		put(11,"Periodici COLL. ANIMALI");
		put(12,"Periodici COLLEZ. CUCINA");
		put(13,"Periodici COLLEZ. MEDICINA");
		put(14,"Periodici COLLEZ. MUSICA");
		put(15,"Periodici COLLEZ. LINGUE STRAN.");
		put(16,"Periodici COLLEZ. BAMBINI");
		put(18,"Periodici COLLEZ. COP/RAC");
		put(19,"Periodici COLLEZ. IN VIDEO");
		put(20,"Enciclopedie");
		put(21,"Enciclopedie ANIMALI");
		put(22,"Enciclopedie CUCINA");
		put(23,"Enciclopedie MEDICINA");
		put(24,"Enciclopedie MUSICA");
		put(25,"Enciclopedie  LINGUE STRANIERE");
		put(28,"Enciclopedie COPERTINE/RACCOGLIT.");
		put(29,"Enciclopedia IN VIDEO");
		put(30,"Riviste");
		put(31,"Riviste di attualità");
		put(32,"Riviste di INFORMATICA E  ELETTR.");
		put(33,"Riviste DI CUCINA");
		put(34,"Riviste di ENIGMISTICA");
		put(35,"Riviste MODA MAGLIA E CUCITO");
		put(36,"Riviste di MUSICA E SPETTACOLO");
		put(37,"Riviste di SPORT");
		put(38,"Riviste di NATURA E ANIMALI");
		put(39,"Riviste di ASTROLOGIA");
		put(40,"Romanzi");
		put(41,"Romanzi di FANTASCIENZA");
		put(42,"Romanzi GIALLI");
		put(43,"Romanzi ROSA");
		put(44,"VARIE LIBRI,\" TASCAB. RACCOLTE");
		put(45,"Fotoromanzi");
		put(46,"Varie ANNUALI (Calendari,\" Agende,\" diari,\"..)");
		put(47,"Varie LIBRI");
		put(50,"Fumetti");
		put(51,"Fumetti BAMBINI");
		put(52 ,"Fumetti FANTASCIENZA E HORROR");
		put(53,"Fumetti GIALLI");
		put(54,"Fumetti ORRORE");
		put(55,"Fumetti WESTERN");
		put(57,"Fumetti Guerra");
		put(59,"Riviste PER BAMBINI");
		put(60,"Motori AUTO - CAMION");
		put(61,"Motori BARCHE - NAUTICA");
		put(62,"Motori MOTO");
		put(63,"Motori SORTIVI");
		put(64,"Motori FUORISTRADA");
		put(65,"Ciclo e Mountain Bike");
		put(70,"Varie ANNUNCI ECONOMICI");
		put(71,"Varie BUSTE A SORPRESA");
		put(72,"Varie CARTINE STRADALI");
		put(73,"Varie FIGURINE");
		put(74,"Varie VIDEO CASSETTE");
		put(75,"Varie POSTER");
		put(76,"Varie RIVISTE ESTERE");
		put(77,"Varie BUSTE FUM. BAMBINI");
		put(78,"Varie BUSTE FOTOROMANZI");
		put(79,"Varie BUSTE");
		put(80,"Quotidiani");
		put(81,"Quotidiani di ECONOMIA");
		put(82,"Quotidiani SPORTIVI");
		put(83,"Quotidiani STRANIERI");
		put(84,"Quotidiani LOCALI");
		put(200,"Enciclopedie Generali");
		put(210,"Letteratura Fascicoli");
		put(220,"Arte");
		put(221,"Corsi Arte");
		put(230,"Musica Classica");
		put(231,"Musica Leggera");
		put(232,"Musica Lirica");
		put(233,"Musica Rock");
		put(234,"Musica Jazz");
		put(240,"Cinema E Film");
		put(250,"Femminili");
		put(251,"Femminili Hobby");
		put(252,"Femminili Lavori");
		put(260,"Formazione Professionale");
		put(270,"Geografia");
		put(280,"Informatica");
		put(290,"Cucina");
		put(291,"Cucina Telematica");
		put(300,"Arredamento");
		put(310,"Ragazzi");
		put(311,"Ragazzi Femmine");
		put(312,"Ragazzi Maschi");
		put(320,"Bricolage");
		put(330,"Collezionismo");
		put(340,"Fotografia");
		put(350,"Giardinaggio");
		put(360,"Sport");
		put(370,"Corsi Lingua");
		put(371,"Corsi Lingua Inglese");
		put(372,"Corsi Lingua Francese");
		put(373,"Corsi Lingua Tedesco");
		put(374,"Corsi Lingua Spagnolo");
		put(375,"Corsi Lingua Russo");
		put(380,"Medicina");
		put(390,"Natura");
		put(400,"Parapsicologia");
		put(410,"Storia");
		put(420,"Storia Settoriale");
		put(421,"Storia Generale");
		put(430,"Religione");
		put(440,"Scienza e Tecnologia");
		put(450,"Fantascienza");
		put(460,"Aviazione");
		put(470,"Turismo");
		put(480,"Tempo Libero");
		put(490,"Modellismo");
		put(500,"Antiquariato");
		put(510,"Coperte e Raccoglitori");
	}
}
