//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.31 at 10:01:08 AM CEST 
//


package example.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://it.dpe.igeriv/inforiv/schemas}CodFiegDl"/>
 *         &lt;element ref="{http://it.dpe.igeriv/inforiv/schemas}CodFiegDl2" minOccurs="0"/>
 *         &lt;element ref="{http://it.dpe.igeriv/inforiv/schemas}CodFiegDl3" minOccurs="0"/>
 *         &lt;element ref="{http://it.dpe.igeriv/inforiv/schemas}CodEdicolaDl"/>
 *         &lt;element ref="{http://it.dpe.igeriv/inforiv/schemas}CodEdicolaDl2" minOccurs="0"/>
 *         &lt;element ref="{http://it.dpe.igeriv/inforiv/schemas}CodEdicolaDl3" minOccurs="0"/>
 *         &lt;element ref="{http://it.dpe.igeriv/inforiv/schemas}RagioneSociale"/>
 *         &lt;element ref="{http://it.dpe.igeriv/inforiv/schemas}Indirizzo"/>
 *         &lt;element ref="{http://it.dpe.igeriv/inforiv/schemas}Localita"/>
 *         &lt;element ref="{http://it.dpe.igeriv/inforiv/schemas}SiglaProvincia"/>
 *         &lt;element ref="{http://it.dpe.igeriv/inforiv/schemas}Cap"/>
 *         &lt;element ref="{http://it.dpe.igeriv/inforiv/schemas}PartitaIva"/>
 *         &lt;element ref="{http://it.dpe.igeriv/inforiv/schemas}CodiceFiscale"/>
 *         &lt;element ref="{http://it.dpe.igeriv/inforiv/schemas}Telefono"/>
 *         &lt;element ref="{http://it.dpe.igeriv/inforiv/schemas}Fax"/>
 *         &lt;element ref="{http://it.dpe.igeriv/inforiv/schemas}Email"/>
 *         &lt;element ref="{http://it.dpe.igeriv/inforiv/schemas}FtpHost"/>
 *         &lt;element ref="{http://it.dpe.igeriv/inforiv/schemas}FtpUser"/>
 *         &lt;element ref="{http://it.dpe.igeriv/inforiv/schemas}FtpPwd"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codFiegDl",
    "codFiegDl2",
    "codFiegDl3",
    "codEdicolaDl",
    "codEdicolaDl2",
    "codEdicolaDl3",
    "ragioneSociale",
    "indirizzo",
    "localita",
    "siglaProvincia",
    "cap",
    "partitaIva",
    "codiceFiscale",
    "telefono",
    "fax",
    "email",
    "ftpHost",
    "ftpUser",
    "ftpPwd"
})
@XmlRootElement(name = "EdicolaInforiv")
public class EdicolaInforiv {

    @XmlElement(name = "CodFiegDl")
    protected int codFiegDl;
    @XmlElement(name = "CodFiegDl2")
    protected Integer codFiegDl2;
    @XmlElement(name = "CodFiegDl3")
    protected Integer codFiegDl3;
    @XmlElement(name = "CodEdicolaDl")
    protected int codEdicolaDl;
    @XmlElement(name = "CodEdicolaDl2")
    protected Integer codEdicolaDl2;
    @XmlElement(name = "CodEdicolaDl3")
    protected Integer codEdicolaDl3;
    @XmlElement(name = "RagioneSociale", required = true)
    protected String ragioneSociale;
    @XmlElement(name = "Indirizzo", required = true)
    protected String indirizzo;
    @XmlElement(name = "Localita", required = true)
    protected String localita;
    @XmlElement(name = "SiglaProvincia", required = true)
    protected String siglaProvincia;
    @XmlElement(name = "Cap", required = true)
    protected String cap;
    @XmlElement(name = "PartitaIva", required = true)
    protected String partitaIva;
    @XmlElement(name = "CodiceFiscale", required = true)
    protected String codiceFiscale;
    @XmlElement(name = "Telefono", required = true)
    protected String telefono;
    @XmlElement(name = "Fax", required = true)
    protected String fax;
    @XmlElement(name = "Email", required = true)
    protected String email;
    @XmlElement(name = "FtpHost", required = true)
    protected String ftpHost;
    @XmlElement(name = "FtpUser", required = true)
    protected String ftpUser;
    @XmlElement(name = "FtpPwd", required = true)
    protected String ftpPwd;

    /**
     * Gets the value of the codFiegDl property.
     * 
     */
    public int getCodFiegDl() {
        return codFiegDl;
    }

    /**
     * Sets the value of the codFiegDl property.
     * 
     */
    public void setCodFiegDl(int value) {
        this.codFiegDl = value;
    }

    /**
     * Gets the value of the codFiegDl2 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCodFiegDl2() {
        return codFiegDl2;
    }

    /**
     * Sets the value of the codFiegDl2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCodFiegDl2(Integer value) {
        this.codFiegDl2 = value;
    }

    /**
     * Gets the value of the codFiegDl3 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCodFiegDl3() {
        return codFiegDl3;
    }

    /**
     * Sets the value of the codFiegDl3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCodFiegDl3(Integer value) {
        this.codFiegDl3 = value;
    }

    /**
     * Gets the value of the codEdicolaDl property.
     * 
     */
    public int getCodEdicolaDl() {
        return codEdicolaDl;
    }

    /**
     * Sets the value of the codEdicolaDl property.
     * 
     */
    public void setCodEdicolaDl(int value) {
        this.codEdicolaDl = value;
    }

    /**
     * Gets the value of the codEdicolaDl2 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCodEdicolaDl2() {
        return codEdicolaDl2;
    }

    /**
     * Sets the value of the codEdicolaDl2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCodEdicolaDl2(Integer value) {
        this.codEdicolaDl2 = value;
    }

    /**
     * Gets the value of the codEdicolaDl3 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCodEdicolaDl3() {
        return codEdicolaDl3;
    }

    /**
     * Sets the value of the codEdicolaDl3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCodEdicolaDl3(Integer value) {
        this.codEdicolaDl3 = value;
    }

    /**
     * Gets the value of the ragioneSociale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRagioneSociale() {
        return ragioneSociale;
    }

    /**
     * Sets the value of the ragioneSociale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRagioneSociale(String value) {
        this.ragioneSociale = value;
    }

    /**
     * Gets the value of the indirizzo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndirizzo() {
        return indirizzo;
    }

    /**
     * Sets the value of the indirizzo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndirizzo(String value) {
        this.indirizzo = value;
    }

    /**
     * Gets the value of the localita property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalita() {
        return localita;
    }

    /**
     * Sets the value of the localita property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalita(String value) {
        this.localita = value;
    }

    /**
     * Gets the value of the siglaProvincia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiglaProvincia() {
        return siglaProvincia;
    }

    /**
     * Sets the value of the siglaProvincia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiglaProvincia(String value) {
        this.siglaProvincia = value;
    }

    /**
     * Gets the value of the cap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCap() {
        return cap;
    }

    /**
     * Sets the value of the cap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCap(String value) {
        this.cap = value;
    }

    /**
     * Gets the value of the partitaIva property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartitaIva() {
        return partitaIva;
    }

    /**
     * Sets the value of the partitaIva property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartitaIva(String value) {
        this.partitaIva = value;
    }

    /**
     * Gets the value of the codiceFiscale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiceFiscale() {
        return codiceFiscale;
    }

    /**
     * Sets the value of the codiceFiscale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiceFiscale(String value) {
        this.codiceFiscale = value;
    }

    /**
     * Gets the value of the telefono property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelefono() {
        return telefono;
    }

    /**
     * Sets the value of the telefono property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelefono(String value) {
        this.telefono = value;
    }

    /**
     * Gets the value of the fax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFax() {
        return fax;
    }

    /**
     * Sets the value of the fax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFax(String value) {
        this.fax = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the ftpHost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFtpHost() {
        return ftpHost;
    }

    /**
     * Sets the value of the ftpHost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFtpHost(String value) {
        this.ftpHost = value;
    }

    /**
     * Gets the value of the ftpUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFtpUser() {
        return ftpUser;
    }

    /**
     * Sets the value of the ftpUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFtpUser(String value) {
        this.ftpUser = value;
    }

    /**
     * Gets the value of the ftpPwd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFtpPwd() {
        return ftpPwd;
    }

    /**
     * Sets the value of the ftpPwd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFtpPwd(String value) {
        this.ftpPwd = value;
    }

}
