//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.31 at 10:01:08 AM CEST 
//


package example.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the example.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Localita_QNAME = new QName("http://it.dpe.igeriv/inforiv/schemas", "Localita");
    private final static QName _CodFiegDl3_QNAME = new QName("http://it.dpe.igeriv/inforiv/schemas", "CodFiegDl3");
    private final static QName _FtpUser_QNAME = new QName("http://it.dpe.igeriv/inforiv/schemas", "FtpUser");
    private final static QName _CodFiegDl2_QNAME = new QName("http://it.dpe.igeriv/inforiv/schemas", "CodFiegDl2");
    private final static QName _Cap_QNAME = new QName("http://it.dpe.igeriv/inforiv/schemas", "Cap");
    private final static QName _Email_QNAME = new QName("http://it.dpe.igeriv/inforiv/schemas", "Email");
    private final static QName _CodiceFiscale_QNAME = new QName("http://it.dpe.igeriv/inforiv/schemas", "CodiceFiscale");
    private final static QName _RagioneSociale_QNAME = new QName("http://it.dpe.igeriv/inforiv/schemas", "RagioneSociale");
    private final static QName _Indirizzo_QNAME = new QName("http://it.dpe.igeriv/inforiv/schemas", "Indirizzo");
    private final static QName _CodFiegDl_QNAME = new QName("http://it.dpe.igeriv/inforiv/schemas", "CodFiegDl");
    private final static QName _SiglaProvincia_QNAME = new QName("http://it.dpe.igeriv/inforiv/schemas", "SiglaProvincia");
    private final static QName _CodEdicolaDl2_QNAME = new QName("http://it.dpe.igeriv/inforiv/schemas", "CodEdicolaDl2");
    private final static QName _Fax_QNAME = new QName("http://it.dpe.igeriv/inforiv/schemas", "Fax");
    private final static QName _PartitaIva_QNAME = new QName("http://it.dpe.igeriv/inforiv/schemas", "PartitaIva");
    private final static QName _FtpPwd_QNAME = new QName("http://it.dpe.igeriv/inforiv/schemas", "FtpPwd");
    private final static QName _Telefono_QNAME = new QName("http://it.dpe.igeriv/inforiv/schemas", "Telefono");
    private final static QName _FtpHost_QNAME = new QName("http://it.dpe.igeriv/inforiv/schemas", "FtpHost");
    private final static QName _CodEdicolaDl3_QNAME = new QName("http://it.dpe.igeriv/inforiv/schemas", "CodEdicolaDl3");
    private final static QName _CodEdicolaDl_QNAME = new QName("http://it.dpe.igeriv/inforiv/schemas", "CodEdicolaDl");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: example.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EdicolaInforivResponse }
     * 
     */
    public EdicolaInforivResponse createEdicolaInforivResponse() {
        return new EdicolaInforivResponse();
    }

    /**
     * Create an instance of {@link EdicolaInforivRequest }
     * 
     */
    public EdicolaInforivRequest createEdicolaInforivRequest() {
        return new EdicolaInforivRequest();
    }

    /**
     * Create an instance of {@link EdicolaInforiv }
     * 
     */
    public EdicolaInforiv createEdicolaInforiv() {
        return new EdicolaInforiv();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://it.dpe.igeriv/inforiv/schemas", name = "Localita")
    public JAXBElement<String> createLocalita(String value) {
        return new JAXBElement<String>(_Localita_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://it.dpe.igeriv/inforiv/schemas", name = "CodFiegDl3")
    public JAXBElement<Integer> createCodFiegDl3(Integer value) {
        return new JAXBElement<Integer>(_CodFiegDl3_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://it.dpe.igeriv/inforiv/schemas", name = "FtpUser")
    public JAXBElement<String> createFtpUser(String value) {
        return new JAXBElement<String>(_FtpUser_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://it.dpe.igeriv/inforiv/schemas", name = "CodFiegDl2")
    public JAXBElement<Integer> createCodFiegDl2(Integer value) {
        return new JAXBElement<Integer>(_CodFiegDl2_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://it.dpe.igeriv/inforiv/schemas", name = "Cap")
    public JAXBElement<String> createCap(String value) {
        return new JAXBElement<String>(_Cap_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://it.dpe.igeriv/inforiv/schemas", name = "Email")
    public JAXBElement<String> createEmail(String value) {
        return new JAXBElement<String>(_Email_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://it.dpe.igeriv/inforiv/schemas", name = "CodiceFiscale")
    public JAXBElement<String> createCodiceFiscale(String value) {
        return new JAXBElement<String>(_CodiceFiscale_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://it.dpe.igeriv/inforiv/schemas", name = "RagioneSociale")
    public JAXBElement<String> createRagioneSociale(String value) {
        return new JAXBElement<String>(_RagioneSociale_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://it.dpe.igeriv/inforiv/schemas", name = "Indirizzo")
    public JAXBElement<String> createIndirizzo(String value) {
        return new JAXBElement<String>(_Indirizzo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://it.dpe.igeriv/inforiv/schemas", name = "CodFiegDl")
    public JAXBElement<Integer> createCodFiegDl(Integer value) {
        return new JAXBElement<Integer>(_CodFiegDl_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://it.dpe.igeriv/inforiv/schemas", name = "SiglaProvincia")
    public JAXBElement<String> createSiglaProvincia(String value) {
        return new JAXBElement<String>(_SiglaProvincia_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://it.dpe.igeriv/inforiv/schemas", name = "CodEdicolaDl2")
    public JAXBElement<Integer> createCodEdicolaDl2(Integer value) {
        return new JAXBElement<Integer>(_CodEdicolaDl2_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://it.dpe.igeriv/inforiv/schemas", name = "Fax")
    public JAXBElement<String> createFax(String value) {
        return new JAXBElement<String>(_Fax_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://it.dpe.igeriv/inforiv/schemas", name = "PartitaIva")
    public JAXBElement<String> createPartitaIva(String value) {
        return new JAXBElement<String>(_PartitaIva_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://it.dpe.igeriv/inforiv/schemas", name = "FtpPwd")
    public JAXBElement<String> createFtpPwd(String value) {
        return new JAXBElement<String>(_FtpPwd_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://it.dpe.igeriv/inforiv/schemas", name = "Telefono")
    public JAXBElement<String> createTelefono(String value) {
        return new JAXBElement<String>(_Telefono_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://it.dpe.igeriv/inforiv/schemas", name = "FtpHost")
    public JAXBElement<String> createFtpHost(String value) {
        return new JAXBElement<String>(_FtpHost_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://it.dpe.igeriv/inforiv/schemas", name = "CodEdicolaDl3")
    public JAXBElement<Integer> createCodEdicolaDl3(Integer value) {
        return new JAXBElement<Integer>(_CodEdicolaDl3_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://it.dpe.igeriv/inforiv/schemas", name = "CodEdicolaDl")
    public JAXBElement<Integer> createCodEdicolaDl(Integer value) {
        return new JAXBElement<Integer>(_CodEdicolaDl_QNAME, Integer.class, null, value);
    }

}
