//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.31 at 10:20:55 AM CEST 
//


package it.dpe.rtae.edicole.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://rtae.dpe.it/edicole/schemas}IdEdicolaRtae" minOccurs="0"/>
 *         &lt;element ref="{http://rtae.dpe.it/edicole/schemas}IdEdicolaPressDi" minOccurs="0"/>
 *         &lt;element ref="{http://rtae.dpe.it/edicole/schemas}CodFiegDl"/>
 *         &lt;element ref="{http://rtae.dpe.it/edicole/schemas}CodEdicolaDl"/>
 *         &lt;element ref="{http://rtae.dpe.it/edicole/schemas}RagioneSociale"/>
 *         &lt;element ref="{http://rtae.dpe.it/edicole/schemas}Indirizzo"/>
 *         &lt;element ref="{http://rtae.dpe.it/edicole/schemas}Localita"/>
 *         &lt;element ref="{http://rtae.dpe.it/edicole/schemas}SiglaProvincia"/>
 *         &lt;element ref="{http://rtae.dpe.it/edicole/schemas}Cap"/>
 *         &lt;element ref="{http://rtae.dpe.it/edicole/schemas}PartitaIva"/>
 *         &lt;element ref="{http://rtae.dpe.it/edicole/schemas}CodiceFiscale"/>
 *         &lt;element ref="{http://rtae.dpe.it/edicole/schemas}Telefono"/>
 *         &lt;element ref="{http://rtae.dpe.it/edicole/schemas}Fax"/>
 *         &lt;element ref="{http://rtae.dpe.it/edicole/schemas}Email"/>
 *         &lt;element ref="{http://rtae.dpe.it/edicole/schemas}DataAttivazione" minOccurs="0"/>
 *         &lt;element ref="{http://rtae.dpe.it/edicole/schemas}DataSospensione" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idEdicolaRtae",
    "idEdicolaPressDi",
    "codFiegDl",
    "codEdicolaDl",
    "ragioneSociale",
    "indirizzo",
    "localita",
    "siglaProvincia",
    "cap",
    "partitaIva",
    "codiceFiscale",
    "telefono",
    "fax",
    "email",
    "dataAttivazione",
    "dataSospensione"
})
@XmlRootElement(name = "EdicolaRtae")
public class EdicolaRtae {

    @XmlElement(name = "IdEdicolaRtae")
    protected Long idEdicolaRtae;
    @XmlElement(name = "IdEdicolaPressDi")
    protected Long idEdicolaPressDi;
    @XmlElement(name = "CodFiegDl")
    protected int codFiegDl;
    @XmlElement(name = "CodEdicolaDl")
    protected int codEdicolaDl;
    @XmlElement(name = "RagioneSociale", required = true)
    protected String ragioneSociale;
    @XmlElement(name = "Indirizzo", required = true)
    protected String indirizzo;
    @XmlElement(name = "Localita", required = true)
    protected String localita;
    @XmlElement(name = "SiglaProvincia", required = true)
    protected String siglaProvincia;
    @XmlElement(name = "Cap", required = true)
    protected String cap;
    @XmlElement(name = "PartitaIva", required = true)
    protected String partitaIva;
    @XmlElement(name = "CodiceFiscale", required = true)
    protected String codiceFiscale;
    @XmlElement(name = "Telefono", required = true)
    protected String telefono;
    @XmlElement(name = "Fax", required = true)
    protected String fax;
    @XmlElement(name = "Email", required = true)
    protected String email;
    @XmlElement(name = "DataAttivazione")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dataAttivazione;
    @XmlElement(name = "DataSospensione")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dataSospensione;

    /**
     * Gets the value of the idEdicolaRtae property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getIdEdicolaRtae() {
        return idEdicolaRtae;
    }

    /**
     * Sets the value of the idEdicolaRtae property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setIdEdicolaRtae(Long value) {
        this.idEdicolaRtae = value;
    }

    /**
     * Gets the value of the idEdicolaPressDi property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getIdEdicolaPressDi() {
        return idEdicolaPressDi;
    }

    /**
     * Sets the value of the idEdicolaPressDi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setIdEdicolaPressDi(Long value) {
        this.idEdicolaPressDi = value;
    }

    /**
     * Gets the value of the codFiegDl property.
     * 
     */
    public int getCodFiegDl() {
        return codFiegDl;
    }

    /**
     * Sets the value of the codFiegDl property.
     * 
     */
    public void setCodFiegDl(int value) {
        this.codFiegDl = value;
    }

    /**
     * Gets the value of the codEdicolaDl property.
     * 
     */
    public int getCodEdicolaDl() {
        return codEdicolaDl;
    }

    /**
     * Sets the value of the codEdicolaDl property.
     * 
     */
    public void setCodEdicolaDl(int value) {
        this.codEdicolaDl = value;
    }

    /**
     * Gets the value of the ragioneSociale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRagioneSociale() {
        return ragioneSociale;
    }

    /**
     * Sets the value of the ragioneSociale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRagioneSociale(String value) {
        this.ragioneSociale = value;
    }

    /**
     * Gets the value of the indirizzo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndirizzo() {
        return indirizzo;
    }

    /**
     * Sets the value of the indirizzo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndirizzo(String value) {
        this.indirizzo = value;
    }

    /**
     * Gets the value of the localita property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalita() {
        return localita;
    }

    /**
     * Sets the value of the localita property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalita(String value) {
        this.localita = value;
    }

    /**
     * Gets the value of the siglaProvincia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiglaProvincia() {
        return siglaProvincia;
    }

    /**
     * Sets the value of the siglaProvincia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiglaProvincia(String value) {
        this.siglaProvincia = value;
    }

    /**
     * Gets the value of the cap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCap() {
        return cap;
    }

    /**
     * Sets the value of the cap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCap(String value) {
        this.cap = value;
    }

    /**
     * Gets the value of the partitaIva property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartitaIva() {
        return partitaIva;
    }

    /**
     * Sets the value of the partitaIva property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartitaIva(String value) {
        this.partitaIva = value;
    }

    /**
     * Gets the value of the codiceFiscale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiceFiscale() {
        return codiceFiscale;
    }

    /**
     * Sets the value of the codiceFiscale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiceFiscale(String value) {
        this.codiceFiscale = value;
    }

    /**
     * Gets the value of the telefono property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelefono() {
        return telefono;
    }

    /**
     * Sets the value of the telefono property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelefono(String value) {
        this.telefono = value;
    }

    /**
     * Gets the value of the fax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFax() {
        return fax;
    }

    /**
     * Sets the value of the fax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFax(String value) {
        this.fax = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the dataAttivazione property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataAttivazione() {
        return dataAttivazione;
    }

    /**
     * Sets the value of the dataAttivazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataAttivazione(XMLGregorianCalendar value) {
        this.dataAttivazione = value;
    }

    /**
     * Gets the value of the dataSospensione property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataSospensione() {
        return dataSospensione;
    }

    /**
     * Sets the value of the dataSospensione property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataSospensione(XMLGregorianCalendar value) {
        this.dataSospensione = value;
    }

}
