//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.31 at 10:20:55 AM CEST 
//


package it.dpe.rtae.edicole.schemas;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.dpe.rtae.edicole.schemas package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Localita_QNAME = new QName("http://rtae.dpe.it/edicole/schemas", "Localita");
    private final static QName _Cap_QNAME = new QName("http://rtae.dpe.it/edicole/schemas", "Cap");
    private final static QName _Email_QNAME = new QName("http://rtae.dpe.it/edicole/schemas", "Email");
    private final static QName _CodiceFiscale_QNAME = new QName("http://rtae.dpe.it/edicole/schemas", "CodiceFiscale");
    private final static QName _RagioneSociale_QNAME = new QName("http://rtae.dpe.it/edicole/schemas", "RagioneSociale");
    private final static QName _IdEdicolaRtae_QNAME = new QName("http://rtae.dpe.it/edicole/schemas", "IdEdicolaRtae");
    private final static QName _Indirizzo_QNAME = new QName("http://rtae.dpe.it/edicole/schemas", "Indirizzo");
    private final static QName _DataAttivazione_QNAME = new QName("http://rtae.dpe.it/edicole/schemas", "DataAttivazione");
    private final static QName _CodFiegDl_QNAME = new QName("http://rtae.dpe.it/edicole/schemas", "CodFiegDl");
    private final static QName _IdEdicolaPressDi_QNAME = new QName("http://rtae.dpe.it/edicole/schemas", "IdEdicolaPressDi");
    private final static QName _SiglaProvincia_QNAME = new QName("http://rtae.dpe.it/edicole/schemas", "SiglaProvincia");
    private final static QName _Fax_QNAME = new QName("http://rtae.dpe.it/edicole/schemas", "Fax");
    private final static QName _Telefono_QNAME = new QName("http://rtae.dpe.it/edicole/schemas", "Telefono");
    private final static QName _PartitaIva_QNAME = new QName("http://rtae.dpe.it/edicole/schemas", "PartitaIva");
    private final static QName _DataSospensione_QNAME = new QName("http://rtae.dpe.it/edicole/schemas", "DataSospensione");
    private final static QName _CodEdicolaDl_QNAME = new QName("http://rtae.dpe.it/edicole/schemas", "CodEdicolaDl");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.dpe.rtae.edicole.schemas
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EdicolaRtae }
     * 
     */
    public EdicolaRtae createEdicolaRtae() {
        return new EdicolaRtae();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rtae.dpe.it/edicole/schemas", name = "Localita")
    public JAXBElement<String> createLocalita(String value) {
        return new JAXBElement<String>(_Localita_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rtae.dpe.it/edicole/schemas", name = "Cap")
    public JAXBElement<String> createCap(String value) {
        return new JAXBElement<String>(_Cap_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rtae.dpe.it/edicole/schemas", name = "Email")
    public JAXBElement<String> createEmail(String value) {
        return new JAXBElement<String>(_Email_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rtae.dpe.it/edicole/schemas", name = "CodiceFiscale")
    public JAXBElement<String> createCodiceFiscale(String value) {
        return new JAXBElement<String>(_CodiceFiscale_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rtae.dpe.it/edicole/schemas", name = "RagioneSociale")
    public JAXBElement<String> createRagioneSociale(String value) {
        return new JAXBElement<String>(_RagioneSociale_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rtae.dpe.it/edicole/schemas", name = "IdEdicolaRtae")
    public JAXBElement<Long> createIdEdicolaRtae(Long value) {
        return new JAXBElement<Long>(_IdEdicolaRtae_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rtae.dpe.it/edicole/schemas", name = "Indirizzo")
    public JAXBElement<String> createIndirizzo(String value) {
        return new JAXBElement<String>(_Indirizzo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rtae.dpe.it/edicole/schemas", name = "DataAttivazione")
    public JAXBElement<XMLGregorianCalendar> createDataAttivazione(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DataAttivazione_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rtae.dpe.it/edicole/schemas", name = "CodFiegDl")
    public JAXBElement<Integer> createCodFiegDl(Integer value) {
        return new JAXBElement<Integer>(_CodFiegDl_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rtae.dpe.it/edicole/schemas", name = "IdEdicolaPressDi")
    public JAXBElement<Long> createIdEdicolaPressDi(Long value) {
        return new JAXBElement<Long>(_IdEdicolaPressDi_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rtae.dpe.it/edicole/schemas", name = "SiglaProvincia")
    public JAXBElement<String> createSiglaProvincia(String value) {
        return new JAXBElement<String>(_SiglaProvincia_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rtae.dpe.it/edicole/schemas", name = "Fax")
    public JAXBElement<String> createFax(String value) {
        return new JAXBElement<String>(_Fax_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rtae.dpe.it/edicole/schemas", name = "Telefono")
    public JAXBElement<String> createTelefono(String value) {
        return new JAXBElement<String>(_Telefono_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rtae.dpe.it/edicole/schemas", name = "PartitaIva")
    public JAXBElement<String> createPartitaIva(String value) {
        return new JAXBElement<String>(_PartitaIva_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rtae.dpe.it/edicole/schemas", name = "DataSospensione")
    public JAXBElement<XMLGregorianCalendar> createDataSospensione(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DataSospensione_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rtae.dpe.it/edicole/schemas", name = "CodEdicolaDl")
    public JAXBElement<Integer> createCodEdicolaDl(Integer value) {
        return new JAXBElement<Integer>(_CodEdicolaDl_QNAME, Integer.class, null, value);
    }

}
